Internal Server Error: /api/subscriptions/add-plan
Traceback (most recent call last):
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdmainu/apps/subscriptions/views.py", line 26, in post
    return self.add_plan(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdmainu/apps/subscriptions/views.py", line 38, in add_plan
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 479, in to_internal_value
    for field in fields:
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/utils/model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
           ^^^^^^^^^^^
AttributeError: module 'apps.subscriptions.models.Plan' has no attribute '_meta'
"POST /api/subscriptions/add-plan HTTP/1.1" 500 135668
Internal Server Error: /api/subscriptions/add-plan
Traceback (most recent call last):
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdmainu/apps/subscriptions/views.py", line 26, in post
    return self.add_plan(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdmainu/apps/subscriptions/views.py", line 38, in add_plan
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 479, in to_internal_value
    for field in fields:
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/utils/model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
           ^^^^^^^^^^^
AttributeError: module 'apps.subscriptions.models.Plan' has no attribute '_meta'
"POST /api/subscriptions/add-plan HTTP/1.1" 500 135668
Internal Server Error: /api/subscriptions/add-plan
Traceback (most recent call last):
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdmainu/apps/subscriptions/views.py", line 26, in post
    return self.add_plan(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdmainu/apps/subscriptions/views.py", line 38, in add_plan
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 479, in to_internal_value
    for field in fields:
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/utils/model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
           ^^^^^^^^^^^
AttributeError: module 'apps.subscriptions.models.Plan' has no attribute '_meta'
"POST /api/subscriptions/add-plan HTTP/1.1" 500 135668
Internal Server Error: /api/subscriptions/add-plan
"POST /api/subscriptions/add-plan HTTP/1.1" 500 135
Internal Server Error: /api/subscriptions/add-plan
"POST /api/subscriptions/add-plan HTTP/1.1" 500 135
Internal Server Error: /api/subscriptions/add-plan
"POST /api/subscriptions/add-plan HTTP/1.1" 500 135
Internal Server Error: /api/subscriptions/add-plan
"POST /api/subscriptions/add-plan HTTP/1.1" 500 135
Internal Server Error: /api/subscriptions/use-promotional-code
"POST /api/subscriptions/use-promotional-code HTTP/1.1" 500 145
Internal Server Error: /api/subscriptions/use-promotional-code
"POST /api/subscriptions/use-promotional-code HTTP/1.1" 500 145
Internal Server Error: /api/subscriptions/use-promotional-code
Traceback (most recent call last):
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /api/subscriptions/use-promotional-code HTTP/1.1" 500 85040
Internal Server Error: /api/subscriptions/use-promotional-code
Traceback (most recent call last):
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samstudiox/devs/mainu/bdenv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /api/subscriptions/use-promotional-code HTTP/1.1" 500 85040
Invalid HTTP_HOST header: 'api.mainu.com.mx'. You may need to add 'api.mainu.com.mx' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.mainu.com.mx'. You may need to add 'api.mainu.com.mx' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'api.mainu.com.mx'. You may need to add 'api.mainu.com.mx' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.mainu.com.mx'. You may need to add 'api.mainu.com.mx' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '100.24.23.100'. You may need to add '100.24.23.100' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv/lib/python3.12/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '100.24.23.100'. You may need to add '100.24.23.100' to ALLOWED_HOSTS.
